# nnwebserver-hpa.yml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: nnwebserver
  selfLink: /apis/autoscaling/v1/namespaces/default/horizontalpodautoscalers/nnwebserver
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: ReplicaSet
    name: nnwebserver
  targetCPUUtilizationPercentage: 80
status:
  currentReplicas: 0
  desiredReplicas: 0
